### ISSUE TITLE
Add TIER as a new sharing Provider

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#24]
Mentz has added TIER as a new sharing provider. But we cannot see TIER in the LIR and we can not yet select an e-scooter for our trip.
The app has to be adapted to this new feature

**Comment by AndreasAtSBB** [comment]
No implementation needed.
New issues do over TIER implementation as well.
The LIR can be filtered by provider, but this is not required, since users often doesn't know who the provider of his prefered mode of transport is. We just use the OSM tags for shared modes, e.g. bicycle_rental, escooter_rental and car_sharing.

**Comment by u233336** [comment]
Done, since no implementation needed
